In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
# multidimensional
b = np.array([[2, 5, 2], [2, 5, 6], [8, 8, 5]])

In [3]:
print(b)

[[2 5 2]
 [2 5 6]
 [8 8 5]]


In [4]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.ones((4, 3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [8]:
np.random.rand(2, 3)

array([[0.7797993 , 0.40134922, 0.11897621],
       [0.14296257, 0.17477094, 0.37474494]])

In [9]:
j = np.random.default_rng()
a = j.integers(0, 5, size=5, endpoint=True)

In [10]:
print('original:', a)
j.shuffle(a)
print('shuffled:', a)
j.permutation(a)
print('permutated:', a)

original: [2 2 5 1 4]
shuffled: [4 5 1 2 2]
permutated: [4 5 1 2 2]


In [11]:
# shuffle realmente muda in-place, por isso não retorna nada
j.shuffle(a)
# já o permutation faz um cópia. Podendo retornar algo e guarda-lo em outra váriavel
perm = j.permutation(a)
perm

array([5, 1, 4, 2, 2], dtype=int64)