In [6]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [9]:
# multidimensional
b = np.array([[2, 5, 2], [2, 5, 6], [8, 8, 5]])

In [8]:
print(b)

[[2 5 2]
 [2 5 6]
 [8 8 5]]


In [10]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
d = np.ones((4, 3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [21]:
np.random.rand(2, 3)

array([[0.52338061, 0.24218776, 0.88498336],
       [0.53222504, 0.14373828, 0.84628088]])

In [36]:
j = np.random.default_rng()
a = j.integers(0, 5, size=5, endpoint=True)

In [39]:
print('original:', a)
j.shuffle(a)
print('shuffled:', a)
j.permutation(a)
print('permutated:', a)

original: [1 2 0 0 4]
shuffled: [1 0 4 2 0]
permutated: [1 0 4 2 0]


In [46]:
# shuffle realmente muda in-place, por isso não retorna nada
j.shuffle(a)
# já o permutation faz um cópia. Podendo retornar algo e guarda-lo em outra váriavel
perm = j.permutation(a)
perm

array([2, 1, 0, 0, 4], dtype=int64)

In [54]:
import pandas as pd
# i want that size will be 4 features per row
c = j.integers(0, 1, size=4*12, endpoint=True).reshape(12, 4)
df = pd.DataFrame(c, columns=["satellite", "missile", "education", "medical"])
df

satellite  missile  education  medical
0           1        1          0        0
1           0        1          1        1
2           0        0          1        1
3           0        1          1        1
4           0        0          0        0
5           0        0          0        1
6           0        1          0        1
7           1        1          1        1
8           1        1          0        0
9           0        1          0        1
10          0        0          0        1
11          1        1          0        0

In [ ]:
X = df
# 1 = democratic, 0 = republican
y = j.integers(0, 1, size=12, )